services:
  web:
    image: httpd:latest
    ports:
      - 80:80
    depends_on:
      - db
  php:
    image: php:fpm
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
